name: PHPUnit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  swoole:
    name: Test for Swoole
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-version: [ '8.0', '8.1' ]
        swoole-version: [ 'v4.5.11', 'v4.6.7', 'v4.7.1', 'v4.8.7', 'master' ]
        exclude:
          - php-version: '8.1'
            swoole-version: 'v4.5.11'
          - php-version: '8.1'
            swoole-version: 'v4.6.7'
          - php-version: '8.1'
            swoole-version: 'v4.7.1'
      max-parallel: 8
    env:
      SW_VERSION: ${{ matrix.swoole-version }}
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
      - name: Setup Swoole
        run: ./.github/swoole.install.sh
      - name: Setup Packages
        run: composer update -o
      - name: Run Test Cases
        run: |
          composer analyse
          composer test
  swow:
    name: Test for Swow
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-version: [ '8.0', '8.1' ]
        swow-version: [ 'v0.1.0-nightly20220116', 'develop' ]
      max-parallel: 4
    env:
      SW_VERSION: ${{ matrix.swow-version }}
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
      - name: Setup Swoole
        run: ./.github/swow.install.sh
      - name: Setup Packages
        run: |
          composer update -o
          composer require "hyperf/engine-swow:^2.0"
      - name: Run Test Cases
        run: |
          composer analyse
          composer test
